### ISSUE TITLE
[BUG] openapi meta produces code that doesn't compile

### ISSUE THREAD

**Issue by wtrocki** [OpenAPITools/openapi-generator#13209]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Generator test does report that .opts() method is missing:

https://github.com/OpenAPITools/openapi-generator/blob/0204bf4ae284d936e4f7cb1ffad314c04d5df9db/modules/openapi-generator/src/main/resources/codegen/generatorClassTest.mustache#L34

DefaultGenerator doesn't seem to be extending `Generator` class thus is missing opts.

https://github.com/OpenAPITools/openapi-generator/blob/0204bf4ae284d936e4f7cb1ffad314c04d5df9db/modules/openapi-generator/src/main/resources/codegen/generatorClass.mustache

##### openapi-generator version

From source, latest release etc.

##### Steps to reproduce

To reproduce:
1. run `openapi-generator meta`.
2. mvn clean install

**Comment by gaborbernat** [comment]
Yeah, this still is the case...
