### ISSUE TITLE
[BUG] [Go] Free-form query parameters are not serialized correctly

### ISSUE THREAD

**Issue by ctreatma** [OpenAPITools/openapi-generator#15946]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The OpenAPI 3.x schema describes a way to specify arbitrary query parameters using ["free-form query parameters"](
https://swagger.io/specification/) (the linked page doesn't have good anchors so you'll have to search for the quoted text on that page to see the example _in situ_).

Given the following example from the page linked above:

```yaml
in: query
name: freeForm
schema:
  type: object
  additionalProperties:
    type: string
style: form
```

If I generate a Go client and use that client to send a request with `freeForm := map[string]string{"search":"something"}`, the client _should_ send a request to the API that looks roughly like this:

`https://example.com/api/endpoint?search=something`

but instead the client sends a request that looks like this:

`https://example.com/api/endpoint?freeForm[search]=something`.

Based on the [OpenAPI specification for serializing query parameters](https://swagger.io/docs/specification/serialization/#query) it appears that generated Go clients use `deepObject`-style serialization for query parameters that are objects, even if a different serialization (in this case, `form`) is specified.

##### openapi-generator version

v6.6.0

##### OpenAPI declaration file content or url

**TODO**:  Working on filling in the remaining fields but wanted to get the issue filed sooner rather than later.

##### Suggest a fix

**TODO** but I think this would be localized to the generated `parameterAddToHeaderOrQuery` function

**Comment by ctreatma** [comment]
Updated external documentation links.  Previous links went to 3.1 docs; updated links show the relevant parts of the 3.0.x specification.

**Comment by xwangbolt** [comment]
+1

**Comment by unasra** [comment]
+1
