### ISSUE TITLE
[REQ] Overall python generators syntax and format improvements

### ISSUE THREAD

**Issue by anis-campos** [OpenAPITools/openapi-generator#16384]
### Is your feature request related to a problem? Please describe.

Following #16377, and seeing that there is still work to be done (#16382, #16378, etc...) , it would be more effective to create a issue to track the advancement

## Describe the solution you'd like

There is several aspects to this issue: 
- Chose a minimal python version to be used ( 3.7 ? ) and make sure the python syntax is properly use in all python generator. some tooling like `pyupgrade`, can point at what needs to be changed by fixing the samples and changing the generator to achieve the same.
- Add type hints 
- Fix the formatting ( once again, tooling to help: isort, black, flake, etc....)

Some optional points:
- check the dependencies, they might be outdated 

## Task list

- [ ] Define the minimal python version ( 3.7 ? )  and update the dependencies version accordingly
- [ ] Make sur the generated code syntaxes is up-to-date 
- [x] Improve the CI  ( see @multani [comment](https://github.com/OpenAPITools/openapi-generator/issues/16384#issuecomment-1726193226))
  - https://github.com/OpenAPITools/openapi-generator/pull/16643
- [x] Improve the type hinting and consider using the Annotated types like in https://github.com/OpenAPITools/openapi-generator/issues/15464
  - #16624
- [ ] TBD

**Comment by anis-campos** [comment]
> Could you perhaps create a [tasklist](https://docs.github.com/en/issues/managing-your-tasks-with-tasklists/creating-a-tasklist) (or something similar) in this issue to track down the different improvements that could be done?

Certanly, it was the main goal behind this issue, any suggestion is welcomed, thanks for that.

**Comment by multani** [comment]
> * [ ]  Improve the CI  ( see @multani [comment](https://github.com/OpenAPITools/openapi-generator/issues/16384#issuecomment-1726193226))

This is a first step to improve the Python CI: https://github.com/OpenAPITools/openapi-generator/pull/16643

**Comment by multani** [comment]
> * [ ]  Define the minimal python version ( 3.7 ? )  and update the dependencies version accordingly

This is now enforced in the CI, Python 3.7 to 3.11 are supported.

The project will consider dropping Python 3.7 once Pydantic v2 will drop support for it: https://github.com/pydantic/pydantic/pull/7188

> * [ ]  Make sur the generated code syntaxes is up-to-date

I don't remember what you meant with this one :sweat_smile: 

> * [ ]  Improve the CI  ( see @multani [comment](https://github.com/OpenAPITools/openapi-generator/issues/16384#issuecomment-1726193226))
>      * [python: run the Python samples tests with GitHub Actions #16643](https://github.com/OpenAPITools/openapi-generator/pull/16643)

The CI now runs most of the client samples tests with all the supported Python versions :+1: 

> * [ ]  Improve the type hinting and consider using the Annotated types like in [[REQ][python-nextgen] Use Annotated with constrained types #15464](https://github.com/OpenAPITools/openapi-generator/issues/15464)
>       
>  * [python: generate Pydantic v2 + typing complete code #16624](https://github.com/OpenAPITools/openapi-generator/pull/16624)

#16624 has been merged now. I proposed #16691 and #16692 to start to improve the typing information.
