### ISSUE TITLE
The execution of `bin/openapi3/{LANG}-petshop.sh` is not included in PR checklist

### ISSUE THREAD

**Issue by autopp** [OpenAPITools/openapi-generator#2070]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Current PR template requires to only run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh`.

> - [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.

However, in fact, `./bin/openapi3/{LANG}-petstore.sh` also needs to be executed. If you push it without executing it, the CI job will fail.
For example, the job failed when I submitted #2068.
https://circleci.com/gh/OpenAPITools/openapi-generator/4649#tests/containers/2

##### openapi-generator version

```
$ git log --oneline -n 1
dd3e6c6a3b (HEAD -> master, origin/master, origin/HEAD) Use actual value of generateSourceCodeOnly in python generator. (#2015)
```

##### OpenAPI declaration file content or url

N/A

##### Command line used for generation

N/A

##### Steps to reproduce

N/A

##### Related issues/PRs

N/A

##### Suggest a fix

Would you like to add `./bin/openapi3/{LANG}-petstore.sh` to the checklist in `.github/PULL_REQUEST_TEMPLATE.md` as well?
